-- CUSTOMER 360

-- LTV (Life Time Value): Total revenue generated by a customer across all completed orders.

-- RFM: Classifies customers based on three signals: 
  -- Recency: How many days since their last purchase
  -- Frequency: How many orders they have placed in total
  -- Monetary: How much they have spent in total

-- Combined, these three signals produce a segment label:
  -- VIP → recent and frequent buyer
  -- Active → bought within the last 90 days
  -- At Risk → no purchase in 90–180 days
  -- Churned → no purchase in over 180 days

-- Churn Risk: Boolean flag for customers with no purchases in the last 90 days.
-- Return Rate: Ratio of refunded orders to total completed orders per customer.

CREATE OR REPLACE MATERIALIZED VIEW e2e_databricks.gold.gold_customer_360 AS

WITH order_stats AS (
  SELECT
    customer_id,
    COUNT(*) AS total_orders,
    SUM(total_amount) AS total_spent, -- LTV
    MAX(order_date) AS last_order_date,
    DATEDIFF(CURRENT_DATE(), MAX(order_date)) AS days_since_last_order
FROM e2e_databricks.silver.silver_orders
WHERE status = 'completed' -- Completed orders only
GROUP BY customer_id
),

returns AS (
  SELECT
    o.customer_id,
    COUNT(*)  AS total_returns
FROM e2e_databricks.silver.silver_orders o
WHERE o.status = 'refunded'
GROUP BY o.customer_id
)

SELECT
  c.customer_id,
  c.full_name,
  c.email,
  c.city,
  c.country,

  -- LTV
  COALESCE(os.total_spent, 0) AS ltv,

  -- RFM
  os.days_since_last_order AS recency_days,
  COALESCE(os.total_orders, 0) AS frequency,
  COALESCE(os.total_spent, 0) AS monetary,

  -- Simple segmentation based on RFM
    CASE
        WHEN os.days_since_last_order <= 30 AND os.total_orders >= 5 THEN 'VIP'
        WHEN os.days_since_last_order <= 90 THEN 'Active'
        WHEN os.days_since_last_order <= 180 THEN 'At Risk'
        ELSE 'Churned'
    END AS customer_segment,

    os.days_since_last_order > 90 AS is_churn_risk,

    -- Ratio de devoluciones
    COALESCE(r.total_returns, 0) AS total_returns,
    ROUND(
        COALESCE(r.total_returns, 0) / NULLIF(os.total_orders, 0), 2
    ) AS return_rate

FROM e2e_databricks.silver.silver_customers c
LEFT JOIN order_stats os ON c.customer_id = os.customer_id
LEFT JOIN returns r ON c.customer_id = r.customer_id;


-- PRODUCT PERFORMANCE (Audience: Product)
-- One row per product with sales and profitability metrics.

-- Gross Revenue: Total revenue before discounts.
-- Net Revenue: Total revenue after discounts.
-- Margin Rate: Profit margin as a percentage of net revenue.
-- Stock Turnover: How many times the current stock has been sold. 
-- A high value means the product moves fast.
-- Return Rate: Ratio of returned orders to total orders for that product.

CREATE OR REPLACE MATERIALIZED VIEW e2e_databricks.gold.gold_product_performance AS

WITH sales AS (
    SELECT
        oi.product_id,
        COUNT(DISTINCT oi.order_id) AS times_ordered,
        SUM(oi.quantity) AS units_sold,
        ROUND(SUM(oi.quantity * oi.unit_price), 2) AS gross_revenue,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)) AS net_revenue
    FROM e2e_databricks.silver.silver_order_items oi
    JOIN e2e_databricks.silver.silver_orders o ON oi.order_id = o.order_id
    WHERE o.status = 'completed'
    GROUP BY oi.product_id
),

returns AS (
    SELECT
        oi.product_id,
        COUNT(DISTINCT o.order_id)  AS returned_orders
    FROM e2e_databricks.silver.silver_order_items oi
    JOIN e2e_databricks.silver.silver_orders o ON oi.order_id = o.order_id
    WHERE o.status = 'refunded'
    GROUP BY oi.product_id
)

SELECT
    p.product_id,
    p.name,
    p.category,
    p.subcategory,
    p.brand,
    p.price_usd,
    p.cost_usd,
    p.stock,

    -- Ventas
    COALESCE(s.units_sold, 0)                                           AS units_sold,
    COALESCE(s.gross_revenue, 0)                                        AS gross_revenue,
    COALESCE(s.net_revenue, 0)                                          AS net_revenue,

    -- Margen
    ROUND(
        (s.net_revenue - (p.cost_usd * s.units_sold))
        / NULLIF(s.net_revenue, 0), 2
    )                                                                   AS margin_rate,

    -- Stock turnover: cuántas veces se "vendió" el stock completo
    ROUND(
        COALESCE(s.units_sold, 0) / NULLIF(p.stock, 0), 2
    )                                                                   AS stock_turnover,

    -- Devoluciones
    COALESCE(r.returned_orders, 0)                                      AS returned_orders,
    ROUND(
        COALESCE(r.returned_orders, 0) / NULLIF(s.times_ordered, 0), 2
    )                                                                   AS return_rate

FROM e2e_databricks.silver.silver_products p
LEFT JOIN sales s    ON p.product_id = s.product_id
LEFT JOIN returns r  ON p.product_id = r.product_id;


-- DAILY OPS SUMMARY (Audience: Operations)
-- One row per day per channel with operational KPIs.

-- GMV (Gross Merchandise Value): Total value of all orders placed that day, regardless of returns or cancellations. This is the top-line number that reflects business volume.
-- Avg Ticket: Average order value per channel per day.
-- Order Breakdown: Count of completed, cancelled, disputed and refunded orders.
-- SLA %: Percentage of shipments delivered within the estimated delivery window.
-- Example: 87% means 87 out of 100 shipments arrived on time that day.

CREATE OR REPLACE MATERIALIZED VIEW e2e_databricks.gold.gold_daily_ops_summary AS

WITH daily_orders AS (
    SELECT
        DATE(order_date) AS order_day,
        channel,
        COUNT(*) AS total_orders,
        ROUND(SUM(total_amount), 2) AS gmv,              
        AVG(total_amount) AS avg_ticket,       
        SUM(CASE WHEN status = 'completed'  THEN 1 ELSE 0 END) AS completed,
        SUM(CASE WHEN status = 'cancelled'  THEN 1 ELSE 0 END) AS cancelled,
        SUM(CASE WHEN status = 'disputed'   THEN 1 ELSE 0 END) AS disputed,
        SUM(CASE WHEN status = 'refunded'   THEN 1 ELSE 0 END) AS refunded
    FROM e2e_databricks.silver.silver_orders
    GROUP BY DATE(order_date), channel
),

daily_delivery_sla AS (
    SELECT
        DATE(shipped_at) AS ship_day,
        COUNT(*) AS total_shipped,
        SUM(
            CASE
                WHEN DATEDIFF(delivered_at, shipped_at) <= estimated_days THEN 1
                ELSE 0
            END
        ) AS delivered_on_time
    FROM e2e_databricks.silver.silver_deliveries
    GROUP BY DATE(shipped_at)
)

SELECT
    o.order_day,
    o.channel,
    o.total_orders,
    o.gmv,
    ROUND(o.avg_ticket, 2) AS avg_ticket,
    o.completed,
    o.cancelled,
    o.disputed,
    o.refunded,

    -- SLA %
    ROUND(
        COALESCE(d.delivered_on_time, 0) / NULLIF(d.total_shipped, 0) * 100, 1
    ) AS sla_pct

FROM daily_orders o
LEFT JOIN daily_delivery_sla d ON o.order_day = d.ship_day;